"""update product table

Revision ID: 6f9f53ec6f0c
Revises: a8526ef1317e
Create Date: 2022-09-15 12:22:33.265064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9f53ec6f0c'
down_revision = 'a8526ef1317e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
